/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class life_knowledge4_videotrimmersample_Brother_Thumbnail */

#ifndef _Included_life_knowledge4_videotrimmersample_Brother_Thumbnail
#define _Included_life_knowledge4_videotrimmersample_Brother_Thumbnail
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
