/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class life_knowledge4_videotrimmersample_Brother */

#ifndef _Included_life_knowledge4_videotrimmersample_Brother
#define _Included_life_knowledge4_videotrimmersample_Brother
#ifdef __cplusplus
extern "C" {
#endif
#undef life_knowledge4_videotrimmersample_Brother_PERMISSIONS_REQUEST_CODE
#define life_knowledge4_videotrimmersample_Brother_PERMISSIONS_REQUEST_CODE 1000L
/*
 * Class:     life_knowledge4_videotrimmersample_Brother
 * Method:    ConvertRGBtoGray
 * Signature: (JJJJII)V
 */
JNIEXPORT void JNICALL Java_life_knowledge4_videotrimmersample_Brother_ConvertRGBtoGray
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jint, jint);

/*
 * Class:     life_knowledge4_videotrimmersample_Brother
 * Method:    getJNIString
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_life_knowledge4_videotrimmersample_Brother_getJNIString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
